### ISSUE TITLE
ImportError: No module named 'serializations'

### ISSUE THREAD

**Issue by nin-jin** [lega911/db_test0#1]
I run docker-machine in Virtual Box on Windows 10

```
docker@docker:~/db_test0$ ./fill.sh
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    import pyorient
  File "/app/pyorient_lib/pyorient/__init__.py", line 8, in <module>
    from serializations import OrientSerialization
ImportError: No module named 'serializations'
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    import pyorient
  File "/app/pyorient_lib/pyorient/__init__.py", line 8, in <module>
    from serializations import OrientSerialization
ImportError: No module named 'serializations'
```

**Comment by lega911** [comment]
It's broken pyorient in github, I've fixed it https://github.com/lega911/db_test0/commit/9190ef4e30b8def381915010294365ce37f3d494
It works well on digital ocean. Try again please.

Also you can run "cd ./pyorient_lib; git checkout v1.4.5; cd .." and run ./fill.sh again.
